# Stage 1 - Build

FROM maven:3.9.9-eclipse-temurin-11 AS builder

WORKDIR /app

# Clone project
RUN git clone -b Master https://github.com/abdelrahmanonline4/sourcecodeseniorwr.git .


RUN sed -i 's/^jdbc.password=.*/jdbc.password=admin123/' src/main/resources/application.properties && \
    sed -i 's/^rabbitmq.username=.*/rabbitmq.username=test/' src/main/resources/application.properties && \
    sed -i 's/^rabbitmq.password=.*/rabbitmq.password=test/' src/main/resources/application.properties

# Build application
RUN mvn clean package -DskipTests



# Stage 2 - Runtime

FROM tomcat:9.0-jdk11-temurin

# Remove default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR from builder
COPY --from=builder /app/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh","run"]